import { useState, useRef } from "react";
import {
  BarChart, Bar, LineChart, Line, PieChart, Pie, Cell,
  XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, AreaChart, Area, Legend,
} from "recharts";
import { useTheme } from "next-themes";
import { Download, Package, AlertTriangle, CheckCircle, Clock, Printer, FileText, File, LayoutDashboard } from "lucide-react";
import { toast } from "sonner";
import { useAuth } from "../context/AuthContext";
import { useInventory } from "../context/InventoryContext";
import { useAssignments } from "../context/AssignmentsContext";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from "../components/ui/dialog";

const COLORS = ["#B0BF00", "#1a1d27", "#94a3b8", "#64748b", "#C5D300", "#8BA000"];

const CARD = "overflow-hidden rounded-[28px] border border-[#B0BF00]/15 bg-white shadow-[0_24px_60px_rgba(15,23,42,0.08)] transition-all duration-300 hover:shadow-[0_26px_70px_rgba(15,23,42,0.12)]";

function escapeHtml(text: string) {
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

function toCsvCell(value: string | number | null | undefined) {
  const stringValue = value === null || value === undefined ? "" : String(value);
  return `"${stringValue.replace(/"/g, '""')}"`;
}

function toCsvRow(values: Array<string | number | null | undefined>) {
  return values.map(toCsvCell).join(",");
}

function normalizeDate(value?: string, endOfDay = false) {
  if (!value) return null;
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return null;
  if (endOfDay) {
    date.setHours(23, 59, 59, 999);
  } else {
    date.setHours(0, 0, 0, 0);
  }
  return date;
}

function isDateWithinRange(dateValue: string | undefined, startDate?: string, endDate?: string) {
  if (!startDate && !endDate) return true;
  const recordDate = normalizeDate(dateValue);
  if (!recordDate) return false;

  const start = normalizeDate(startDate);
  const end = normalizeDate(endDate, true);

  if (start && recordDate < start) return false;
  if (end && recordDate > end) return false;
  return true;
}

export default function Reports() {
  const [reportStartDate, setReportStartDate] = useState("");
  const [reportEndDate, setReportEndDate] = useState("");
  const [showPrintPreview] = useState(false);
  const [showFormatDialog, setShowFormatDialog] = useState(false);
  const printRef = useRef<HTMLDivElement>(null);
  const { user } = useAuth();
  const { resolvedTheme } = useTheme();
  const { inventory, loading: inventoryLoading } = useInventory();
  const { assignments, loading: assignmentsLoading } = useAssignments();
  const isDark = resolvedTheme === "dark";
  const chartGrid = isDark ? "#314865" : "#f1f5f9";
  const chartAxis = isDark ? "#f5f9ff" : "#94a3b8";
  const chartTooltip = isDark
    ? {
        backgroundColor: "#0d1a2b",
        border: "1px solid #314865",
        borderRadius: "10px",
        color: "#f5f9ff",
        fontSize: "11px",
      }
    : {
        backgroundColor: "#fff",
        border: "1px solid #e2e8f0",
        borderRadius: "8px",
        fontSize: "11px",
      };
  const chartLegend = isDark
    ? { fontSize: "10px", color: "#f5f9ff" }
    : { fontSize: "10px" };
  const chartTitleClass = isDark ? "text-slate-100" : "text-gray-800";
  const chartIconClass = isDark ? "text-slate-300 hover:text-slate-100" : "text-gray-400 hover:text-gray-600";

  const reportInventory = inventory.filter((item) =>
    isDateWithinRange(item.purchaseDate || item.createdAt, reportStartDate, reportEndDate)
  );
  const reportAssignments = assignments.filter((assignment) =>
    isDateWithinRange(assignment.dateAssigned, reportStartDate, reportEndDate)
  );

  const handleExport = (type: string) => {
    if (type === "Full") {
      handleExportCSV();
      return;
    }

    toast.success(`${type} report exported successfully.`);
  };

  const handleGenerateReport = (format: "pdf" | "csv") => {
    setShowFormatDialog(false);
    
    if (format === "pdf") {
      handleDownloadPDF();
    } else {
      // Generate CSV
      handleExportCSV();
    }
  };

  const handleExportCSVLegacy = () => {
    // Create CSV content with professional table format
    const csvRows = [];
    
    // === HEADER SECTION ===
    csvRows.push("DIGITAL MINDS BPO SERVICES INC.");
    csvRows.push("INVENTORY MANAGEMENT SYSTEM - COMPREHENSIVE REPORT");
    csvRows.push(`Report Generated: ${new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric", hour: "2-digit", minute: "2-digit" })}`);
    csvRows.push(`Generated by: ${generatedBy}`);
    csvRows.push(""); // Separator
    csvRows.push("═══════════════════════════════════════════════════════════════════════════════════════════════════════════");
    csvRows.push(""); // Separator
    
    // === EXECUTIVE SUMMARY ===
    csvRows.push("EXECUTIVE SUMMARY");
    csvRows.push("─────────────────────────────────────────────────────────────────────────────────────────────────────────");
    csvRows.push(""); // Separator
    
    // Summary table with proper alignment
    csvRows.push("Metric,Value,Details");
    csvRows.push(`Total Assets,${totalAssets},Across all categories`);
    csvRows.push(`Assets In Stock,${totalInStock},"${totalAssets > 0 ? Math.round((totalInStock / totalAssets) * 100) : 0}% of total inventory"`);
    csvRows.push(`Low Stock Items,${totalLowStock},Requires restocking`);
    csvRows.push(`Out of Stock Items,${totalOutOfStock},Urgent action needed`);
    csvRows.push(`Under Maintenance,${totalUnderMaintenance},Currently being serviced`);
    csvRows.push(`Total Inventory Value,"₱${totalInventoryValue.toLocaleString()}",Current market value`);
    csvRows.push(""); // Separator
    csvRows.push(""); // Separator
    
    // === STOCK DISTRIBUTION BY CATEGORY ===
    csvRows.push("STOCK DISTRIBUTION BY CATEGORY");
    csvRows.push("─────────────────────────────────────────────────────────────────────────────────────────────────────────");
    csvRows.push(""); // Separator
    csvRows.push("Category,In Stock,Low Stock,Out of Stock,Total Quantity,Percentage");
    
    const totalItems = stockByType.reduce((sum, item) => sum + item.total, 0);
    stockByType.forEach(item => {
      const percentage = totalItems > 0 ? Math.round((item.total / totalItems) * 100) : 0;
      csvRows.push(`"${item.name}",${item.inStock},${item.lowStock},${item.outOfStock},${item.total},${percentage}%`);
    });
    
    // Add totals row
    csvRows.push(`"TOTAL",${stockByType.reduce((sum, item) => sum + item.inStock, 0)},${stockByType.reduce((sum, item) => sum + item.lowStock, 0)},${stockByType.reduce((sum, item) => sum + item.outOfStock, 0)},${totalItems},100%`);
    csvRows.push(""); // Separator
    csvRows.push(""); // Separator
    
    // === DETAILED INVENTORY LISTING ===
    csvRows.push("DETAILED INVENTORY LISTING");
    csvRows.push("─────────────────────────────────────────────────────────────────────────────────────────────────────────");
    csvRows.push(""); // Separator
    csvRows.push("Asset Name,SKU,Category,Brand,Model,Serial Number,Location,Qty,Unit Price,Total Value,Status,Condition,Purchase Date");
    
    // Sort inventory by category then by asset name
    const sortedInventory = [...reportInventory].sort((a, b) => {
      if (a.category !== b.category) return a.category.localeCompare(b.category);
      return a.assetName.localeCompare(b.assetName);
    });
    
    sortedInventory.forEach(item => {
      csvRows.push(
        `\"${item.assetName}\",\"${item.sku}\",\"${item.category}\",\"${item.brand}\",\"${item.model}\",\"${item.serialNumber}\",\"${item.location}\",${item.quantity},\"₱${item.price.toLocaleString()}\",\"₱${(item.price * item.quantity).toLocaleString()}\",\"${item.stockStatus}\",\"${item.condition || 'N/A'}\",\"${item.purchaseDate || 'N/A'}\"`
      );
    });
    csvRows.push(""); // Separator
    csvRows.push(""); // Separator
    
    // === TOP ASSETS BY VALUE ===
    csvRows.push("TOP ASSETS BY VALUE");
    csvRows.push("─────────────────────────────────────────────────────────────────────────────────────────────────────────");
    csvRows.push(""); // Separator
    csvRows.push("Rank,Asset Name,SKU,Category,Quantity,Unit Price,Total Value,Status,Condition");
    
    topAssets.slice(0, 10).forEach((item, index) => {
      csvRows.push(
        `${index + 1},"${item.name}","${item.sku}","${item.category}",${item.qty},"₱${item.price.toLocaleString()}","₱${item.totalValue.toLocaleString()}","${item.stockStatus}","${item.condition}"`
      );
    });
    csvRows.push(""); // Separator
    csvRows.push(""); // Separator
    
    // === INVENTORY VALUE BREAKDOWN ===
    csvRows.push("INVENTORY VALUE BREAKDOWN BY CATEGORY");
    csvRows.push("─────────────────────────────────────────────────────────────────────────────────────────────────────────");
    csvRows.push(""); // Separator
    csvRows.push("Category,Total Value,Percentage of Total");
    
    const totalValue = inventoryValueByCategory.reduce((sum, cat) => sum + cat.value, 0);
    inventoryValueByCategory.forEach(cat => {
      const percentage = totalValue > 0 ? Math.round((cat.value / totalValue) * 100) : 0;
      csvRows.push(`"${cat.name}","₱${cat.value.toLocaleString()}",${percentage}%`);
    });
    csvRows.push(`"TOTAL","₱${totalValue.toLocaleString()}",100%`);
    csvRows.push(""); // Separator
    csvRows.push(""); // Separator
    
    // === ASSET CONDITION SUMMARY ===
    csvRows.push("ASSET CONDITION SUMMARY");
    csvRows.push("─────────────────────────────────────────────────────────────────────────────────────────────────────────");
    csvRows.push(""); // Separator
    csvRows.push("Condition,Quantity,Percentage");
    
    const totalConditionItems = conditionData.reduce((sum, d) => sum + d.value, 0);
    conditionData.forEach(item => {
      const percentage = totalConditionItems > 0 ? Math.round((item.value / totalConditionItems) * 100) : 0;
      csvRows.push(`"${item.name}",${item.value},${percentage}%`);
    });
    csvRows.push(`"TOTAL",${totalConditionItems},100%`);
    csvRows.push(""); // Separator
    csvRows.push(""); // Separator
    
    // === LOW STOCK ALERTS ===
    if (lowStockAlerts.length > 0) {
      csvRows.push("⚠️ LOW STOCK ALERTS - IMMEDIATE ATTENTION REQUIRED");
      csvRows.push("─────────────────────────────────────────────────────────────────────────────────────────────────────────");
      csvRows.push(""); // Separator
      csvRows.push("Priority,Asset Name,SKU,Category,Current Qty,Minimum Qty,Shortage,Status,Action Required");
      
      lowStockAlerts.forEach((item, index) => {
        const shortage = item.minimum - item.current;
        const priority = item.current === 0 ? "CRITICAL" : shortage > 10 ? "HIGH" : "MEDIUM";
        const status = item.current === 0 ? "OUT OF STOCK" : "LOW STOCK";
        const action = item.current === 0 ? "Order Immediately" : `Restock ${shortage} units`;
        
        csvRows.push(
          `"${priority}","${item.name}","${item.sku}","${item.category}",${item.current},${item.minimum},${shortage},"${status}","${action}"`
        );
      });
      csvRows.push(""); // Separator
      csvRows.push(""); // Separator
    }
    
    // === MONTHLY ACQUISITION TREND ===
    csvRows.push("MONTHLY ASSET ACTIVITY (Selected Date Range)");
    csvRows.push("─────────────────────────────────────────────────────────────────────────────────────────────────────────");
    csvRows.push(""); // Separator
    csvRows.push("Month,Inventory Added,Assignments Logged,Net Activity");
    
    monthlyAcquisition.forEach(month => {
      const netChange = month.acquired + month.assigned;
      const changeIndicator = netChange > 0 ? `+${netChange}` : netChange.toString();
      csvRows.push(`"${month.month}",${month.acquired},${month.assigned},"${changeIndicator}"`);
    });
    
    const totalAcquired = monthlyAcquisition.reduce((sum, m) => sum + m.acquired, 0);
    const totalAssigned = monthlyAcquisition.reduce((sum, m) => sum + m.assigned, 0);
    const netTotal = totalAcquired + totalAssigned;
    csvRows.push(`"TOTAL",${totalAcquired},${totalAssigned},"${netTotal > 0 ? '+' : ''}${netTotal}"`);
    csvRows.push(""); // Separator
    csvRows.push(""); // Separator
    
    // === FOOTER ===
    csvRows.push("═══════════════════════════════════════════════════════════════════════════════════════════════════════════");
    csvRows.push(""); // Separator
    csvRows.push("REPORT NOTES:");
    csvRows.push("• This report contains confidential inventory information");
    csvRows.push("• All values are in Philippine Peso (₱)");
    csvRows.push("• Low Stock threshold is based on Minimum Quantity settings");
    csvRows.push(`• Report includes ${reportInventory.length} unique inventory items with total quantity of ${totalAssets} assets`);
    csvRows.push("• For questions or discrepancies, contact the Inventory Management Team");
    csvRows.push(""); // Separator
    csvRows.push("═══════════════════════════════════════════════════════════════════════════════════════════════════════════");
    csvRows.push(`Digital Minds BPO Services Inc. © ${new Date().getFullYear()} | Inventory Management System v1.0`);
    
    // Create CSV blob and download
    const csvContent = csvRows.join("\n");
    const blob = new Blob(["\uFEFF" + csvContent], { type: "text/csv;charset=utf-8;" }); // BOM for proper Excel encoding
    const link = document.createElement("a");
    const url = URL.createObjectURL(blob);
    link.setAttribute("href", url);
    link.setAttribute("download", `DigitalMinds_Inventory_Report_${new Date().toISOString().split('T')[0]}.csv`);
    link.style.visibility = "hidden";
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    
    toast.success("Professional CSV report downloaded successfully!");
  };

  const handleExportCSV = () => {
    const csvRows: string[] = [];
    const generatedAt = new Date().toLocaleString("en-US", {
      year: "numeric",
      month: "long",
      day: "numeric",
      hour: "2-digit",
      minute: "2-digit",
    });
    const selectedDateRange = `${reportStartDate || "Start"} to ${reportEndDate || "End"}`;
    const totalItems = stockByType.reduce((sum, item) => sum + item.total, 0);
    const totalCategoryValue = inventoryValueByCategory.reduce((sum, category) => sum + category.value, 0);
    const totalConditionItems = conditionData.reduce((sum, condition) => sum + condition.value, 0);
    const totalAcquired = monthlyAcquisition.reduce((sum, month) => sum + month.acquired, 0);
    const totalAssigned = monthlyAcquisition.reduce((sum, month) => sum + month.assigned, 0);
    const sortedInventory = [...reportInventory].sort((a, b) => {
      const categoryA = a.category || "Uncategorized";
      const categoryB = b.category || "Uncategorized";

      if (categoryA !== categoryB) {
        return categoryA.localeCompare(categoryB);
      }

      return a.assetName.localeCompare(b.assetName);
    });

    const sortedAssignments = [...reportAssignments].sort((a, b) => {
      return (b.dateAssigned || "").localeCompare(a.dateAssigned || "");
    });

    const addBlankRow = () => {
      csvRows.push("");
    };

    const addSection = (title: string) => {
      addBlankRow();
      csvRows.push(toCsvRow([title]));
    };

    csvRows.push(toCsvRow(["Digital Minds BPO Services Inc."]));
    csvRows.push(toCsvRow(["Inventory Management System Report"]));
    csvRows.push(toCsvRow(["Generated At", generatedAt]));
    csvRows.push(toCsvRow(["Generated By", generatedBy]));
    csvRows.push(toCsvRow(["Report Range", selectedDateRange]));
    csvRows.push(toCsvRow(["Filtered Inventory Records", reportInventory.length]));
    csvRows.push(toCsvRow(["Filtered Assignment Records", reportAssignments.length]));

    addSection("Executive Summary");
    csvRows.push(toCsvRow(["Metric", "Value", "Notes"]));
    csvRows.push(toCsvRow(["Total Assets", totalAssets, "Combined quantity across filtered inventory records"]));
    csvRows.push(toCsvRow(["In Stock", totalInStock, `${totalAssets > 0 ? Math.round((totalInStock / totalAssets) * 100) : 0}% of filtered asset quantity`]));
    csvRows.push(toCsvRow(["Low Stock", totalLowStock, "Items below the defined minimum quantity"]));
    csvRows.push(toCsvRow(["Out of Stock", totalOutOfStock, "Items with zero available quantity"]));
    csvRows.push(toCsvRow(["Under Maintenance", totalUnderMaintenance, "Assignment records currently marked under maintenance"]));
    csvRows.push(toCsvRow(["Inventory Value", `PHP ${totalInventoryValue.toLocaleString()}`, "Calculated from quantity x unit price"]));

    addSection("Stock Distribution by Category");
    csvRows.push(toCsvRow(["Category", "In Stock", "Low Stock", "Out of Stock", "Total Quantity", "Share of Total"]));
    stockByType.forEach((item) => {
      const percentage = totalItems > 0 ? `${Math.round((item.total / totalItems) * 100)}%` : "0%";
      csvRows.push(
        toCsvRow([
          item.name,
          item.inStock,
          item.lowStock,
          item.outOfStock,
          item.total,
          percentage,
        ])
      );
    });
    csvRows.push(
      toCsvRow([
        "Total",
        stockByType.reduce((sum, item) => sum + item.inStock, 0),
        stockByType.reduce((sum, item) => sum + item.lowStock, 0),
        stockByType.reduce((sum, item) => sum + item.outOfStock, 0),
        totalItems,
        "100%",
      ])
    );

    addSection("Detailed Inventory Listing");
    csvRows.push(
      toCsvRow([
        "Asset Name",
        "SKU",
        "Category",
        "Brand",
        "Model",
        "Serial Number",
        "Location",
        "Quantity",
        "Minimum Quantity",
        "Unit Price",
        "Total Value",
        "Status",
        "Condition",
        "Purchase Date",
      ])
    );
    sortedInventory.forEach((item) => {
      csvRows.push(
        toCsvRow([
          item.assetName,
          item.sku,
          item.category || "Uncategorized",
          item.brand || "N/A",
          item.model || "N/A",
          item.serialNumber || "N/A",
          item.location || "N/A",
          item.quantity,
          item.minimumQuantity,
          `PHP ${item.price.toLocaleString()}`,
          `PHP ${(item.price * item.quantity).toLocaleString()}`,
          item.stockStatus,
          item.condition || "Unspecified",
          item.purchaseDate || item.createdAt || "N/A",
        ])
      );
    });

    addSection("Top Assets by Value");
    csvRows.push(toCsvRow(["Rank", "Asset Name", "SKU", "Category", "Quantity", "Unit Price", "Total Value", "Status", "Condition"]));
    topAssets.slice(0, 10).forEach((item, index) => {
      csvRows.push(
        toCsvRow([
          index + 1,
          item.name,
          item.sku,
          item.category,
          item.qty,
          `PHP ${item.price.toLocaleString()}`,
          `PHP ${item.totalValue.toLocaleString()}`,
          item.stockStatus,
          item.condition,
        ])
      );
    });

    addSection("Inventory Value by Category");
    csvRows.push(toCsvRow(["Category", "Total Value", "Share of Value"]));
    inventoryValueByCategory.forEach((category) => {
      const percentage = totalCategoryValue > 0 ? `${Math.round((category.value / totalCategoryValue) * 100)}%` : "0%";
      csvRows.push(toCsvRow([category.name, `PHP ${category.value.toLocaleString()}`, percentage]));
    });
    csvRows.push(toCsvRow(["Total", `PHP ${totalCategoryValue.toLocaleString()}`, "100%"]));

    addSection("Asset Condition Summary");
    csvRows.push(toCsvRow(["Condition", "Quantity", "Share of Condition Totals"]));
    conditionData.forEach((condition) => {
      const percentage = totalConditionItems > 0 ? `${Math.round((condition.value / totalConditionItems) * 100)}%` : "0%";
      csvRows.push(toCsvRow([condition.name, condition.value, percentage]));
    });
    csvRows.push(toCsvRow(["Total", totalConditionItems, "100%"]));

    addSection("Low Stock Alerts");
    csvRows.push(toCsvRow(["Priority", "Asset Name", "SKU", "Category", "Current Qty", "Minimum Qty", "Shortage", "Status", "Recommended Action"]));
    if (lowStockAlerts.length === 0) {
      csvRows.push(toCsvRow(["No low stock alerts within the selected date range"]));
    } else {
      lowStockAlerts.forEach((item) => {
        const shortage = item.minimum - item.current;
        const priority = item.current === 0 ? "Critical" : shortage > 10 ? "High" : "Medium";
        const status = item.current === 0 ? "Out of Stock" : "Low Stock";
        const action = item.current === 0 ? "Reorder immediately" : `Restock ${shortage} unit(s)`;

        csvRows.push(
          toCsvRow([
            priority,
            item.name,
            item.sku,
            item.category,
            item.current,
            item.minimum,
            shortage,
            status,
            action,
          ])
        );
      });
    }

    addSection("Monthly Asset Activity");
    csvRows.push(toCsvRow(["Month", "Inventory Added", "Assignments Logged", "Net Activity"]));
    monthlyAcquisition.forEach((month) => {
      const net = month.acquired + month.assigned;
      csvRows.push(
        toCsvRow([
          month.month,
          month.acquired,
          month.assigned,
          `${net > 0 ? "+" : ""}${net}`,
        ])
      );
    });
    csvRows.push(toCsvRow(["Total", totalAcquired, totalAssigned, `${totalAcquired + totalAssigned > 0 ? "+" : ""}${totalAcquired + totalAssigned}`]));

    addSection("Assignment Log");
    csvRows.push(toCsvRow(["Date Assigned", "Asset", "SKU", "Category", "Assigned To", "Department", "Workstation", "Floor", "Status"]));
    if (sortedAssignments.length === 0) {
      csvRows.push(toCsvRow(["No assignment activity found within the selected date range"]));
    } else {
      sortedAssignments.forEach((assignment) => {
        csvRows.push(
          toCsvRow([
            assignment.dateAssigned || "N/A",
            assignment.assetName || "N/A",
            assignment.assetSKU || "N/A",
            assignment.assetCategory || "N/A",
            assignment.assignedTo || "N/A",
            assignment.department || "N/A",
            assignment.workstation || "N/A",
            assignment.floor || "N/A",
            assignment.status || "N/A",
          ])
        );
      });
    }

    addSection("Report Notes");
    csvRows.push(toCsvRow(["This export reflects the active report filters and live database-backed records in the system."]));
    csvRows.push(toCsvRow(["Currency values are shown in Philippine Peso using PHP formatting."]));
    csvRows.push(toCsvRow([`This report includes ${reportInventory.length} filtered inventory record(s) and ${reportAssignments.length} filtered assignment record(s).`]));

    const csvContent = csvRows.join("\n");
    const blob = new Blob(["\uFEFF" + csvContent], { type: "text/csv;charset=utf-8;" });
    const link = document.createElement("a");
    const url = URL.createObjectURL(blob);

    link.setAttribute("href", url);
    link.setAttribute("download", `DigitalMinds_Inventory_Report_${new Date().toISOString().split("T")[0]}.csv`);
    link.style.visibility = "hidden";
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);

    toast.success("Enhanced CSV report downloaded successfully!");
  };

  if (inventoryLoading || assignmentsLoading) {
    return (
      <div className="flex items-center justify-center h-64">
        <div className="text-center">
          <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-[#B0BF00] mx-auto mb-2"></div>
          <p className="text-sm text-gray-500">Loading reports...</p>
        </div>
      </div>
    );
  }

  // Calculate real stats from database
  const totalAssets = reportInventory.reduce((sum, item) => sum + item.quantity, 0);
  const totalInStock = reportInventory.filter(i => i.stockStatus === "In Stock").reduce((sum, item) => sum + item.quantity, 0);
  const totalLowStock = reportInventory.filter(i => i.stockStatus === "Low Stock").reduce((sum, item) => sum + item.quantity, 0);
  const totalOutOfStock = reportInventory.filter(i => i.stockStatus === "Out of Stock").reduce((sum, item) => sum + item.quantity, 0);
  const totalUnderMaintenance = reportAssignments.filter(a => a.status === "Under Maintenance").length;
  const totalInventoryValue = reportInventory.reduce((sum, item) => sum + (item.price * item.quantity), 0);
  const reportCategories = Array.from(
    new Set(reportInventory.map((item) => item.category || "Uncategorized"))
  ).sort((a, b) => a.localeCompare(b));

  const reportSummaryCards = [
    {
      label: "Total Assets",
      value: totalAssets.toString(),
      description: "All tracked items across categories and locations.",
      icon: Package,
      accent: "from-[#f7fad8] to-white",
      iconClass: "text-[#7f8f00]",
    },
    {
      label: "In Stock",
      value: totalInStock.toString(),
      description: `${totalAssets > 0 ? Math.round((totalInStock / totalAssets) * 100) : 0}% of all assets are ready for use.`,
      icon: CheckCircle,
      accent: "from-emerald-50 to-white",
      iconClass: "text-emerald-600",
    },
    {
      label: "Needs Attention",
      value: (totalLowStock + totalOutOfStock).toString(),
      description: "Low stock and out of stock items that need action.",
      icon: AlertTriangle,
      accent: "from-amber-50 to-white",
      iconClass: "text-amber-600",
    },
    {
      label: "Inventory Value",
      value: `₱${totalInventoryValue.toLocaleString()}`,
      description: "Current total value of the inventory in the system.",
      icon: Clock,
      accent: "from-slate-50 to-white",
      iconClass: "text-slate-700",
    },
  ];

  // Stock by category with real data
  const stockByType = (() => {
    return reportCategories.map(cat => {
      const items = reportInventory.filter(i => (i.category || "Uncategorized") === cat);
      return {
        name: cat,
        inStock: items.filter(i => i.stockStatus === "In Stock").reduce((s, i) => s + i.quantity, 0),
        lowStock: items.filter(i => i.stockStatus === "Low Stock").reduce((s, i) => s + i.quantity, 0),
        outOfStock: items.filter(i => i.stockStatus === "Out of Stock").reduce((s, i) => s + i.quantity, 0),
        total: items.reduce((s, i) => s + i.quantity, 0),
      };
    }).filter(cat => cat.total > 0); // Only show categories with items
  })();

  // Monthly inventory and assignment activity from the selected date range
  const monthlyAcquisition = (() => {
    const monthlyCounts = new Map<string, { acquired: number; assigned: number; sortDate: number }>();

    reportInventory.forEach((item) => {
      const recordDate = item.purchaseDate || item.createdAt;
      if (!recordDate) return;

      const purchaseDate = new Date(recordDate);
      if (Number.isNaN(purchaseDate.getTime())) return;

      const monthKey = purchaseDate.toLocaleDateString("en-US", {
        month: "short",
        year: "numeric",
      });

      const current = monthlyCounts.get(monthKey) || {
        acquired: 0,
        assigned: 0,
        sortDate: new Date(purchaseDate.getFullYear(), purchaseDate.getMonth(), 1).getTime(),
      };
      current.acquired += item.quantity;
      monthlyCounts.set(monthKey, current);
    });

    reportAssignments.forEach((assignment) => {
      if (!assignment.dateAssigned) return;

      const assignedDate = new Date(assignment.dateAssigned);
      if (Number.isNaN(assignedDate.getTime())) return;

      const monthKey = assignedDate.toLocaleDateString("en-US", {
        month: "short",
        year: "numeric",
      });

      const current = monthlyCounts.get(monthKey) || {
        acquired: 0,
        assigned: 0,
        sortDate: new Date(assignedDate.getFullYear(), assignedDate.getMonth(), 1).getTime(),
      };
      current.assigned += 1;
      monthlyCounts.set(monthKey, current);
    });

    return Array.from(monthlyCounts.entries())
      .map(([month, value]) => ({
        month,
        acquired: value.acquired,
        assigned: value.assigned,
        sortDate: value.sortDate,
      }))
      .sort((a, b) => a.sortDate - b.sortDate)
      .map(({ sortDate: _sortDate, ...entry }) => entry);
  })();

  // Condition data with real data
  const conditionData = (() => {
    const conditions: Record<string, number> = {};

    reportInventory.forEach((item) => {
      const condition = item.condition?.trim() || "Unspecified";
      conditions[condition] = (conditions[condition] || 0) + item.quantity;
    });
    
    const colors: Record<string, string> = {
      "Excellent": "#B0BF00",
      "Good": isDark ? "#5b8def" : "#1a1d27",
      "Fair": "#94a3b8",
      "Poor": "#ef4444",
      "Damaged": "#dc2626",
      "Unspecified": "#64748b",
    };
    
    return Object.entries(conditions)
      .filter(([_, value]) => value > 0)
      .map(([name, value]) => ({
        name,
        value,
        color: colors[name] || "#64748b",
      }));
  })();
  const totalConditionItems = conditionData.reduce((sum, item) => sum + item.value, 0);

  // Inventory value by category with real data
  const inventoryValueByCategory = (() => {
    const categoryValues = reportCategories.map(cat => {
      const items = reportInventory.filter(i => (i.category || "Uncategorized") === cat);
      const value = items.reduce((s, i) => s + (i.price * i.quantity), 0);
      return { name: cat, value };
    }).filter(cat => cat.value > 0);
    
    const total = categoryValues.reduce((s, c) => s + c.value, 0);
    
    return categoryValues.map(cat => ({
      ...cat,
      percentage: total > 0 ? Math.round((cat.value / total) * 100) : 0,
    }));
  })();

  // Top assets by value with real data
  const topAssets = reportInventory
    .map(item => ({
      name: item.assetName,
      sku: item.sku,
      category: item.category,
      qty: item.quantity,
      price: item.price,
      totalValue: item.price * item.quantity,
      stockStatus: item.stockStatus,
      assetStatus: item.assetStatus,
      condition: item.condition || "Good",
    }))
    .sort((a, b) => b.totalValue - a.totalValue)
    .slice(0, 8);

  // Low stock alerts with real data
  const lowStockAlerts = reportInventory
    .filter(item => item.stockStatus === "Low Stock" || item.stockStatus === "Out of Stock")
    .map(item => ({
      name: item.assetName,
      sku: item.sku,
      current: item.quantity,
      minimum: item.minQuantity,
      category: item.category,
    }))
    .sort((a, b) => a.current - b.current)
    .slice(0, 10);

  const currentDate = new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });
  const generatedBy = user ? `${user.name} (${user.role})` : "System User";
  const selectedDateRange = reportStartDate || reportEndDate
    ? `${reportStartDate || "Beginning"} to ${reportEndDate || "Present"}`
    : "All available records";

  const handleDownloadPDF = () => {
    const printWindow = window.open("", "_blank", "width=1200,height=900");

    if (!printWindow) {
      toast.error("Unable to open the PDF preview window. Please allow pop-ups and try again.");
      return;
    }

    const stockRows = stockByType
      .map(
        (item) => `
          <tr>
            <td>${escapeHtml(item.name)}</td>
            <td class="center in-stock">${item.inStock}</td>
            <td class="center low-stock">${item.lowStock}</td>
            <td class="center out-stock">${item.outOfStock}</td>
            <td class="right strong">${item.total}</td>
          </tr>
        `
      )
      .join("");

    const topAssetRows = topAssets
      .slice(0, 10)
      .map(
        (item) => `
          <tr>
            <td>
              <div class="strong">${escapeHtml(item.name)}</div>
              <div class="muted mono">${escapeHtml(item.sku)}</div>
            </td>
            <td>${escapeHtml(item.category)}</td>
            <td class="center">${item.qty}</td>
            <td class="right">PHP ${item.price.toLocaleString()}</td>
            <td class="right strong">PHP ${item.totalValue.toLocaleString()}</td>
            <td class="center">${escapeHtml(item.stockStatus)}</td>
          </tr>
        `
      )
      .join("");

    const lowStockRows = lowStockAlerts.length > 0
      ? lowStockAlerts
          .map(
            (item) => `
              <tr>
                <td>
                  <div class="strong">${escapeHtml(item.name)}</div>
                  <div class="muted mono">${escapeHtml(item.sku)}</div>
                </td>
                <td>${escapeHtml(item.category)}</td>
                <td class="center">${item.current}</td>
                <td class="center">${item.minimum}</td>
                <td class="center">
                  <span class="badge ${item.current === 0 ? "badge-red" : "badge-amber"}">
                    ${item.current === 0 ? "Out of Stock" : "Low Stock"}
                  </span>
                </td>
              </tr>
            `
          )
          .join("")
      : `
          <tr>
            <td colspan="5" class="empty">No low stock alerts in the selected range.</td>
          </tr>
        `;

    const conditionCards = conditionData
      .map(
        (item) => `
          <div class="condition-card">
            <span class="condition-dot" style="background:${item.color};"></span>
            <div class="strong">${escapeHtml(item.name)}</div>
            <div class="condition-value">${item.value}</div>
          </div>
        `
      )
      .join("");

    const monthlyRows = monthlyAcquisition
      .map(
        (item) => `
          <tr>
            <td>${escapeHtml(item.month)}</td>
            <td class="center">${item.acquired}</td>
            <td class="center">${item.assigned}</td>
            <td class="center strong">${item.acquired + item.assigned}</td>
          </tr>
        `
      )
      .join("");

    const html = `
      <!DOCTYPE html>
      <html lang="en">
        <head>
          <meta charset="UTF-8" />
          <meta name="viewport" content="width=device-width, initial-scale=1.0" />
          <title>Digital Minds Inventory Report</title>
          <style>
            * { box-sizing: border-box; }
            body {
              margin: 0;
              font-family: Arial, Helvetica, sans-serif;
              background: #eef2e2;
              color: #0f172a;
            }
            .page {
              width: 210mm;
              margin: 0 auto;
              background: #ffffff;
              padding: 18mm 16mm;
            }
            .hero {
              display: flex;
              justify-content: space-between;
              gap: 16px;
              align-items: flex-start;
              border-bottom: 3px solid #b0bf00;
              padding-bottom: 18px;
            }
            .logo {
              height: 52px;
              width: auto;
              display: block;
              margin-bottom: 10px;
            }
            .eyebrow {
              font-size: 11px;
              font-weight: 700;
              letter-spacing: 0.18em;
              text-transform: uppercase;
              color: #7f8f00;
            }
            h1 {
              margin: 8px 0 6px;
              font-size: 28px;
              line-height: 1.1;
            }
            .meta {
              text-align: right;
              font-size: 12px;
              color: #475569;
              line-height: 1.7;
            }
            .summary-grid {
              display: grid;
              grid-template-columns: repeat(3, 1fr);
              gap: 12px;
              margin: 22px 0;
            }
            .summary-card {
              border: 1px solid #dbe4f0;
              border-radius: 16px;
              padding: 14px;
              background: linear-gradient(180deg, #f8fbeb 0%, #ffffff 100%);
            }
            .summary-card h3 {
              margin: 0 0 8px;
              font-size: 11px;
              letter-spacing: 0.12em;
              text-transform: uppercase;
              color: #6b7280;
            }
            .summary-value {
              font-size: 28px;
              font-weight: 700;
              margin-bottom: 4px;
            }
            .summary-copy {
              font-size: 12px;
              color: #64748b;
            }
            .section {
              margin-top: 22px;
            }
            .section h2 {
              margin: 0 0 10px;
              font-size: 17px;
              border-bottom: 1px solid #dbe4f0;
              padding-bottom: 8px;
            }
            table {
              width: 100%;
              border-collapse: collapse;
            }
            th, td {
              border-bottom: 1px solid #e7edf5;
              padding: 10px 8px;
              font-size: 12px;
              vertical-align: top;
            }
            th {
              background: #eef4fb;
              text-align: left;
              font-size: 11px;
              text-transform: uppercase;
              letter-spacing: 0.08em;
            }
            .center { text-align: center; }
            .right { text-align: right; }
            .strong { font-weight: 700; }
            .muted { color: #64748b; }
            .mono { font-family: "Courier New", monospace; font-size: 11px; }
            .in-stock { color: #047857; }
            .low-stock { color: #d97706; }
            .out-stock { color: #dc2626; }
            .badge {
              display: inline-block;
              padding: 4px 8px;
              border-radius: 999px;
              font-size: 10px;
              font-weight: 700;
              text-transform: uppercase;
            }
            .badge-red {
              background: #fee2e2;
              color: #b91c1c;
            }
            .badge-amber {
              background: #fef3c7;
              color: #b45309;
            }
            .conditions {
              display: grid;
              grid-template-columns: repeat(5, 1fr);
              gap: 10px;
            }
            .condition-card {
              border: 1px solid #dbe4f0;
              border-radius: 14px;
              padding: 12px;
              text-align: center;
              background: #f8fafc;
            }
            .condition-dot {
              width: 12px;
              height: 12px;
              border-radius: 999px;
              display: inline-block;
              margin-bottom: 8px;
            }
            .condition-value {
              margin-top: 6px;
              font-size: 22px;
              font-weight: 700;
            }
            .empty {
              text-align: center;
              color: #64748b;
              padding: 18px 8px;
            }
            .footer {
              margin-top: 26px;
              padding-top: 12px;
              border-top: 2px solid #dbe4f0;
              display: flex;
              justify-content: space-between;
              font-size: 11px;
              color: #64748b;
            }
            @page {
              size: A4;
              margin: 12mm;
            }
            @media print {
              body {
                background: #ffffff;
              }
              .page {
                width: auto;
                margin: 0;
                padding: 0;
              }
            }
          </style>
        </head>
        <body>
          <div class="page">
            <section class="hero">
              <div>
                <img
                  class="logo"
                  src="https://cdn.digitalmindsbpo.com/storage/2021/11/cropped-Digital_Minds_Logo_Original.png"
                  alt="Digital Minds BPO"
                />
                <div class="eyebrow">Inventory Management System</div>
                <h1>Asset Summary Report</h1>
              </div>
              <div class="meta">
                <div><strong>Generated on:</strong> ${escapeHtml(currentDate)}</div>
                <div><strong>Generated by:</strong> ${escapeHtml(generatedBy)}</div>
                <div><strong>Date range:</strong> ${escapeHtml(selectedDateRange)}</div>
              </div>
            </section>

            <section class="summary-grid">
              <article class="summary-card">
                <h3>Total Assets</h3>
                <div class="summary-value">${totalAssets}</div>
                <div class="summary-copy">Across all categories in the selected range.</div>
              </article>
              <article class="summary-card">
                <h3>Assets in Stock</h3>
                <div class="summary-value">${totalInStock}</div>
                <div class="summary-copy">${totalAssets > 0 ? Math.round((totalInStock / totalAssets) * 100) : 0}% of total inventory is ready for use.</div>
              </article>
              <article class="summary-card">
                <h3>Total Value</h3>
                <div class="summary-value">PHP ${totalInventoryValue.toLocaleString()}</div>
                <div class="summary-copy">Current estimated value of tracked assets.</div>
              </article>
            </section>

            <section class="section">
              <h2>Stock Distribution by Category</h2>
              <table>
                <thead>
                  <tr>
                    <th>Category</th>
                    <th class="center">In Stock</th>
                    <th class="center">Low Stock</th>
                    <th class="center">Out of Stock</th>
                    <th class="right">Total</th>
                  </tr>
                </thead>
                <tbody>${stockRows}</tbody>
              </table>
            </section>

            <section class="section">
              <h2>Top Assets by Value</h2>
              <table>
                <thead>
                  <tr>
                    <th>Asset</th>
                    <th>Category</th>
                    <th class="center">Qty</th>
                    <th class="right">Unit Price</th>
                    <th class="right">Total Value</th>
                    <th class="center">Status</th>
                  </tr>
                </thead>
                <tbody>${topAssetRows}</tbody>
              </table>
            </section>

            <section class="section">
              <h2>Low Stock Alerts</h2>
              <table>
                <thead>
                  <tr>
                    <th>Asset</th>
                    <th>Category</th>
                    <th class="center">Current</th>
                    <th class="center">Minimum</th>
                    <th class="center">Status</th>
                  </tr>
                </thead>
                <tbody>${lowStockRows}</tbody>
              </table>
            </section>

            <section class="section">
              <h2>Asset Condition Summary</h2>
              <div class="conditions">${conditionCards}</div>
            </section>

            <section class="section">
              <h2>Monthly Asset Activity</h2>
              <table>
                <thead>
                  <tr>
                    <th>Month</th>
                    <th class="center">Inventory Added</th>
                    <th class="center">Assignments</th>
                    <th class="center">Net Activity</th>
                  </tr>
                </thead>
                <tbody>${monthlyRows}</tbody>
              </table>
            </section>

            <footer class="footer">
              <span>Digital Minds BPO Services Inc.</span>
              <span>Inventory Management System Report</span>
            </footer>
          </div>
        </body>
      </html>
    `;

    printWindow.document.open();
    printWindow.document.write(html);
    printWindow.document.close();
    printWindow.focus();

    window.setTimeout(() => {
      printWindow.print();
    }, 700);

    toast.success("Use Save as PDF in the print dialog to download.");
  };

  return (
    <>
      <div className="space-y-5">
        <div className={CARD}>
          <div className={`px-5 py-6 md:px-6 md:py-7 ${isDark ? "bg-slate-900" : "bg-white"}`}>
            <div className="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between">
              <div className="max-w-2xl">
                <div className={`inline-flex items-center gap-2 rounded-full border px-3 py-1 text-[11px] font-semibold uppercase tracking-[0.2em] ${isDark ? "border-slate-700 bg-slate-800 text-[#d8e56b]" : "border-[#B0BF00]/20 bg-slate-50 text-[#7f8f00]"}`}>
                  <LayoutDashboard className="h-3.5 w-3.5" />
                  Reports Overview
                </div>
                <h2 className="mt-3 text-2xl font-bold tracking-tight text-slate-900 md:text-3xl">
                  Reports & Analytics
                </h2>
              </div>

              <div className="flex flex-col gap-3 sm:flex-row sm:flex-wrap sm:items-center">
                <div className="flex flex-wrap items-center gap-3">
                  <div className="flex items-center gap-2">
                    <span className="text-xs font-medium text-slate-500">Start Date:</span>
                    <input
                      type="date"
                      value={reportStartDate}
                      onChange={(e) => setReportStartDate(e.target.value)}
                      className="h-11 rounded-2xl border border-slate-200 bg-white px-3 text-sm text-slate-700 outline-none shadow-sm focus:border-[#B0BF00]"
                    />
                  </div>
                  <div className="flex items-center gap-2">
                    <span className="text-xs font-medium text-slate-500">End Date:</span>
                    <input
                      type="date"
                      value={reportEndDate}
                      onChange={(e) => setReportEndDate(e.target.value)}
                      className="h-11 rounded-2xl border border-slate-200 bg-white px-3 text-sm text-slate-700 outline-none shadow-sm focus:border-[#B0BF00]"
                    />
                  </div>
                </div>
                <button
                  onClick={() => setShowFormatDialog(true)}
                  className="inline-flex items-center justify-center gap-2 rounded-2xl bg-[#B0BF00] px-4 py-2.5 text-sm font-semibold text-white shadow-[0_14px_30px_rgba(176,191,0,0.28)] transition-colors hover:bg-[#9aaa00]"
                >
                  <Printer className="h-4 w-4" />
                  Generate Report
                </button>
                <button
                  onClick={() => handleExport("Full")}
                  className="inline-flex items-center justify-center gap-2 rounded-2xl border border-slate-200 bg-white px-4 py-2.5 text-sm font-semibold text-slate-600 shadow-sm transition-colors hover:bg-slate-50"
                >
                  <Download className="h-4 w-4" />
                  Export
                </button>
              </div>
            </div>
          </div>
        </div>

        <div className="grid grid-cols-1 gap-4 md:grid-cols-2 xl:grid-cols-4">
          {reportSummaryCards.map((card) => {
            const Icon = card.icon;
            return (
              <div
                key={card.label}
                className={`overflow-hidden rounded-3xl border p-5 shadow-[0_20px_45px_rgba(15,23,42,0.08)] ${isDark ? "border-slate-700 bg-slate-900" : "border-slate-200 bg-white"}`}
              >
                <div className="flex items-start justify-between gap-3">
                  <div>
                    <p className="text-xs font-semibold uppercase tracking-[0.24em] text-slate-500">
                      {card.label}
                    </p>
                    <p className="mt-3 text-2xl font-bold tracking-tight text-slate-900">
                      {card.value}
                    </p>
                  </div>
                  <div className={`rounded-2xl border p-3 shadow-sm ${isDark ? "border-slate-700 bg-slate-800" : "border-slate-200 bg-slate-50"}`}>
                    <Icon className={`h-5 w-5 ${card.iconClass}`} />
                  </div>
                </div>
                <p className="mt-4 text-sm leading-6 text-slate-600">{card.description}</p>
              </div>
            );
          })}
        </div>

        {/* Charts Row 1 */}
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-5">
          {/* Stock by Category */}
          <div className={`${CARD} p-5`}>
            <div className="flex items-center justify-between mb-4">
              <h3 className={`text-sm font-semibold ${chartTitleClass}`}>Stock by Asset Type</h3>
              <button onClick={() => handleExport("Stock by Type")} className={`rounded p-1 ${chartIconClass}`}>
                <Download className="w-3.5 h-3.5" />
              </button>
            </div>
            <ResponsiveContainer width="100%" height={220}>
              <BarChart data={stockByType} barSize={14} barCategoryGap="30%">
                <CartesianGrid strokeDasharray="3 3" stroke={chartGrid} vertical={false} />
                <XAxis dataKey="name" tick={{ fontSize: 9, fill: chartAxis }} axisLine={false} tickLine={false} angle={-15} textAnchor="end" height={50} />
                <YAxis tick={{ fontSize: 10, fill: chartAxis }} axisLine={false} tickLine={false} />
                <Tooltip
                  contentStyle={chartTooltip}
                />
                <Legend wrapperStyle={{ ...chartLegend, paddingTop: "8px" }} />
                <Bar dataKey="inStock" fill={isDark ? "#d7e25f" : "#B0BF00"} name="In Stock" radius={[3, 3, 0, 0]} />
                <Bar dataKey="lowStock" fill={isDark ? "#fbbf24" : "#f97316"} name="Low Stock" radius={[3, 3, 0, 0]} />
                <Bar dataKey="outOfStock" fill={isDark ? "#f87171" : "#ef4444"} name="Out of Stock" radius={[3, 3, 0, 0]} />
              </BarChart>
            </ResponsiveContainer>
          </div>

          {/* Asset Condition Distribution */}
          <div className={`${CARD} p-5`}>
            <div className="flex items-center justify-between mb-4">
              <h3 className={`text-sm font-semibold ${chartTitleClass}`}>Asset Condition</h3>
              <button onClick={() => handleExport("Condition")} className={`rounded p-1 ${chartIconClass}`}>
                <Download className="w-3.5 h-3.5" />
              </button>
            </div>
            <div className="flex flex-col items-center">
              <ResponsiveContainer width="100%" height={160}>
                <PieChart>
                  <Pie data={conditionData} cx="50%" cy="50%" innerRadius={45} outerRadius={70} paddingAngle={2} dataKey="value" strokeWidth={0}>
                    {conditionData.map((entry, index) => (
                      <Cell key={`condition-cell-${entry.name}-${index}`} fill={entry.color} />
                    ))}
                  </Pie>
                  <Tooltip
                    wrapperStyle={{ zIndex: 40, outline: "none" }}
                    content={({ active, payload }) => {
                      if (!active || !payload?.length) return null;
                      const item = payload[0]?.payload as { name: string; value: number; color: string };
                      const percentage = totalConditionItems > 0
                        ? Math.round((item.value / totalConditionItems) * 100)
                        : 0;

                      return (
                        <div
                          className={`min-w-[150px] rounded-xl border px-3 py-2.5 shadow-xl ${
                            isDark
                              ? "border-slate-700 bg-slate-900 text-slate-100"
                              : "border-slate-200 bg-white text-slate-900"
                          }`}
                        >
                          <div className="flex items-center gap-2">
                            <span
                              className="h-2.5 w-2.5 rounded-full"
                              style={{ backgroundColor: item.color }}
                            />
                            <p className="text-xs font-semibold">{item.name}</p>
                          </div>
                          <p className={`mt-2 text-[11px] ${isDark ? "text-slate-300" : "text-slate-600"}`}>
                            Quantity: <span className="font-semibold">{item.value}</span>
                          </p>
                          <p className={`text-[11px] ${isDark ? "text-slate-300" : "text-slate-600"}`}>
                            Share: <span className="font-semibold">{percentage}%</span>
                          </p>
                        </div>
                      );
                    }}
                  />
                </PieChart>
              </ResponsiveContainer>
              <div className="grid grid-cols-3 gap-x-4 gap-y-1.5 w-full mt-2">
                {conditionData.map((d, i) => (
                  <div key={i} className="flex items-center gap-1.5">
                    <span className="w-2 h-2 rounded-full flex-shrink-0" style={{ backgroundColor: d.color }} />
                    <span className="text-[10px] text-slate-500">{d.name} ({d.value})</span>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </div>

        {/* Inventory Value by Category */}
        <div className={`${CARD} p-5`}>
          <div className="flex items-center justify-between mb-4">
            <h3 className={`text-sm font-semibold ${chartTitleClass}`}>Inventory Value Distribution by Category</h3>
            <button onClick={() => handleExport("Value Distribution")} className={`rounded p-1 ${chartIconClass}`}>
              <Download className="w-3.5 h-3.5" />
            </button>
          </div>
          <ResponsiveContainer width="100%" height={220}>
            <BarChart data={inventoryValueByCategory} layout="vertical" barSize={20}>
              <CartesianGrid strokeDasharray="3 3" stroke={chartGrid} horizontal={false} />
              <XAxis type="number" tick={{ fontSize: 10, fill: chartAxis }} axisLine={false} tickLine={false} />
              <YAxis dataKey="name" type="category" tick={{ fontSize: 10, fill: chartAxis }} axisLine={false} tickLine={false} width={100} />
              <Tooltip
                contentStyle={chartTooltip}
                formatter={(value: number) => `₱${value.toLocaleString()}`}
              />
              <Bar dataKey="value" fill={isDark ? "#d7e25f" : "#B0BF00"} radius={[0, 4, 4, 0]} />
            </BarChart>
          </ResponsiveContainer>
        </div>

        {/* Charts Row 2 */}
        <div className={`${CARD} p-5`}>
          <div className="flex items-center justify-between mb-4">
            <h3 className={`text-sm font-semibold ${chartTitleClass}`}>Monthly Asset Activity</h3>
            <button onClick={() => handleExport("Acquisitions")} className={`rounded p-1 ${chartIconClass}`}>
              <Download className="w-3.5 h-3.5" />
            </button>
          </div>
          <ResponsiveContainer width="100%" height={200}>
            <AreaChart data={monthlyAcquisition}>
              <CartesianGrid strokeDasharray="3 3" stroke={chartGrid} vertical={false} />
              <XAxis dataKey="month" tick={{ fontSize: 11, fill: chartAxis }} axisLine={false} tickLine={false} />
              <YAxis tick={{ fontSize: 11, fill: chartAxis }} axisLine={false} tickLine={false} />
              <Tooltip contentStyle={chartTooltip} />
              <Legend wrapperStyle={{ ...chartLegend, fontSize: "11px" }} />
              <Area type="monotone" dataKey="acquired" stroke={isDark ? "#d7e25f" : "#B0BF00"} fill={isDark ? "#d7e25f" : "#B0BF00"} fillOpacity={isDark ? 0.2 : 0.15} strokeWidth={2} name="Inventory Added" />
              <Area type="monotone" dataKey="assigned" stroke={isDark ? "#60a5fa" : "#2563eb"} fill={isDark ? "#60a5fa" : "#2563eb"} fillOpacity={isDark ? 0.16 : 0.1} strokeWidth={2} name="Assignments" />
            </AreaChart>
          </ResponsiveContainer>
        </div>

        {/* Tables Row */}
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-5">
          {/* Top Assets */}
          <div className={`${CARD} p-5`}>
            <div className="flex items-center justify-between mb-4">
              <h3 className={`text-sm font-semibold ${chartTitleClass}`}>Top Assets by Value</h3>
              <button onClick={() => handleExport("Top Assets")} className={`rounded p-1 ${chartIconClass}`}>
                <Download className="w-3.5 h-3.5" />
              </button>
            </div>
            <table className="w-full">
              <thead>
                <tr className={`border-b ${isDark ? "border-[#314865] bg-slate-900" : "border-gray-200 bg-slate-50"}`}>
                  <th className="text-left pb-2 text-[10px] font-semibold uppercase text-slate-400">Asset</th>
                  <th className="text-right pb-2 text-[10px] font-semibold uppercase text-slate-400">Qty</th>
                  <th className="text-right pb-2 text-[10px] font-semibold uppercase text-slate-400">Value</th>
                </tr>
              </thead>
              <tbody className={`divide-y ${isDark ? "divide-[#314865]" : "divide-gray-100"}`}>
                {topAssets.slice(0, 5).map((item, i) => (
                  <tr key={i}>
                    <td className="py-2.5">
                      <p className="text-xs font-medium text-slate-700">{item.name}</p>
                      <p className="text-[10px] font-mono text-slate-400">{item.sku}</p>
                    </td>
                    <td className="py-2.5 text-right text-xs text-slate-600">{item.qty}</td>
                    <td className="py-2.5 text-right text-xs font-semibold text-slate-800">₱{item.totalValue.toLocaleString()}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>

          {/* Low Stock Alerts */}
          <div className={`${CARD} p-5`}>
            <div className="flex items-center justify-between mb-4">
              <h3 className={`text-sm font-semibold ${chartTitleClass}`}>Low Stock Alerts</h3>
              <span className={`text-[10px] font-semibold px-2 py-0.5 rounded-full border ${isDark ? "bg-red-500/15 text-red-300 border-red-500/20" : "bg-red-50 text-red-500 border-red-100"}`}>
                {lowStockAlerts.length} assets
              </span>
            </div>
            <div className="space-y-3">
              {lowStockAlerts.map((item, i) => {
                const pct = item.minimum > 0 ? Math.min((item.current / item.minimum) * 100, 100) : 0;
                const isOut = item.current === 0;
                return (
                  <div key={i} className="space-y-1">
                    <div className="flex items-center justify-between">
                      <div>
                        <p className="text-xs font-medium text-slate-700">{item.name}</p>
                        <p className="text-[10px] text-slate-400">{item.category} · {item.sku}</p>
                      </div>
                      <div className="text-right">
                        <span className={`text-xs font-semibold ${isOut ? "text-red-500" : "text-orange-500"}`}>
                          {item.current} / {item.minimum}
                        </span>
                        <p className="text-[10px] text-slate-400">current / min</p>
                      </div>
                    </div>
                    <div className={`h-1.5 rounded-full overflow-hidden ${isDark ? "bg-[#132338]" : "bg-gray-100"}`}>
                      <div
                        className={`h-full rounded-full ${isOut ? "bg-red-400" : "bg-orange-400"}`}
                        style={{ width: `${pct}%` }}
                      />
                    </div>
                  </div>
                );
              })}
            </div>
            <button className="mt-4 w-full text-xs text-[#B0BF00] hover:underline font-medium">
              View all low stock assets →
            </button>
          </div>
        </div>
      </div>

      {/* Printable Report Template */}
      {showPrintPreview && (
        <div
          id="print-content"
          ref={printRef}
          data-report-theme="light"
          className="report-light hidden print:block fixed inset-0 bg-white z-50 overflow-auto"
          style={{ display: showPrintPreview ? "block" : "none" }}
        >
          <div className="report-light max-w-[8.5in] mx-auto bg-white p-8" data-report-theme="light">
            {/* Report Header */}
            <div className="report-surface mb-6 border-b-2 border-[#B0BF00] pb-6">
              <div className="flex items-start justify-between">
                <div>
                  <img
                    src="https://cdn.digitalmindsbpo.com/wp-content/uploads/2021/11/cropped-Digital_Minds_Logo_Original.png"
                    alt="Digital Minds BPO"
                    className="h-12 mb-3"
                  />
                  <p className="report-muted text-xs">Digital Minds BPO Services Incorporated</p>
                </div>
                <div className="text-right">
                  <h1 className="report-heading mb-1 text-2xl font-bold">Asset Summary Report</h1>
                  <p className="report-muted text-xs">Generated on: {currentDate}</p>
                  <p className="report-muted text-xs">Generated by: {generatedBy}</p>
                </div>
              </div>
            </div>

            {/* Summary Statistics */}
            <div className="grid grid-cols-3 gap-4 mb-8">
              <div className="report-surface rounded-lg border border-[#dbe4f0] bg-gradient-to-br from-[#f7fad8] to-white p-4">
                <p className="mb-1 text-xs font-medium text-[#7f8f00]">Total Assets</p>
                <p className="text-3xl font-bold text-[#0f172a]">{totalAssets}</p>
                <p className="mt-1 text-xs text-[#64748b]">Across all categories</p>
              </div>
              <div className="report-surface rounded-lg border border-[#dbe4f0] bg-gradient-to-br from-emerald-50 to-white p-4">
                <p className="mb-1 text-xs font-medium text-emerald-700">Total Assets in Stock</p>
                <p className="text-3xl font-bold text-emerald-900">{totalInStock}</p>
                <p className="mt-1 text-xs text-emerald-700">{totalAssets > 0 ? Math.round((totalInStock / totalAssets) * 100) : 0}% of total inventory</p>
              </div>
              <div className="report-surface rounded-lg border border-[#dbe4f0] bg-gradient-to-br from-[#eef4fb] to-white p-4">
                <p className="mb-1 text-xs font-medium text-[#1f4f8c]">Total Inventory Value</p>
                <p className="text-3xl font-bold text-[#0f172a]">₱{totalInventoryValue.toLocaleString()}</p>
                <p className="mt-1 text-xs text-[#64748b]">Current market value</p>
              </div>
            </div>

            {/* Asset Distribution by Category */}
            <div className="mb-8">
              <h2 className="report-heading mb-4 border-b border-[#dbe4f0] pb-2 text-lg font-bold">
                Asset Distribution by Category
              </h2>
              <table className="report-surface w-full border-collapse">
                <thead>
                  <tr className="border-y border-[#dbe4f0] bg-[#eef4fb]">
                    <th className="px-3 py-2 text-left text-xs font-semibold text-[#0f172a]">Category</th>
                    <th className="px-3 py-2 text-center text-xs font-semibold text-[#0f172a]">In Stock</th>
                    <th className="px-3 py-2 text-center text-xs font-semibold text-[#0f172a]">Low Stock</th>
                    <th className="px-3 py-2 text-center text-xs font-semibold text-[#0f172a]">Out of Stock</th>
                    <th className="px-3 py-2 text-right text-xs font-semibold text-[#0f172a]">Total</th>
                  </tr>
                </thead>
                <tbody>
                  {stockByType.map((item, i) => (
                    <tr key={i} className="border-b border-[#eef4fb]">
                      <td className="px-3 py-2 text-sm text-[#0f172a]">{item.name}</td>
                      <td className="px-3 py-2 text-center text-sm font-medium text-emerald-700">{item.inStock}</td>
                      <td className="px-3 py-2 text-center text-sm font-medium text-amber-600">{item.lowStock}</td>
                      <td className="px-3 py-2 text-center text-sm font-medium text-red-600">{item.outOfStock}</td>
                      <td className="px-3 py-2 text-right text-sm font-semibold text-[#0f172a]">{item.total}</td>
                    </tr>
                  ))}
                  <tr className="border-t-2 border-[#dbe4f0] bg-[#f8fafc] font-semibold">
                    <td className="px-3 py-2 text-sm text-[#0f172a]">Total</td>
                    <td className="px-3 py-2 text-center text-sm text-emerald-700">{stockByType.reduce((sum, item) => sum + item.inStock, 0)}</td>
                    <td className="px-3 py-2 text-center text-sm text-amber-600">{stockByType.reduce((sum, item) => sum + item.lowStock, 0)}</td>
                    <td className="px-3 py-2 text-center text-sm text-red-600">{stockByType.reduce((sum, item) => sum + item.outOfStock, 0)}</td>
                    <td className="px-3 py-2 text-right text-sm text-[#0f172a]">{totalAssets}</td>
                  </tr>
                </tbody>
              </table>
            </div>

            {/* Detailed Asset Inventory */}
            <div className="mb-8">
              <h2 className="report-heading mb-4 border-b border-[#dbe4f0] pb-2 text-lg font-bold">
                Detailed Asset Inventory
              </h2>
              <table className="report-surface w-full border-collapse text-xs">
                <thead>
                  <tr className="border-y border-[#dbe4f0] bg-[#eef4fb]">
                    <th className="px-2 py-2 text-left text-[10px] font-semibold uppercase text-[#0f172a]">Name</th>
                    <th className="px-2 py-2 text-left text-[10px] font-semibold uppercase text-[#0f172a]">SKU</th>
                    <th className="px-2 py-2 text-left text-[10px] font-semibold uppercase text-[#0f172a]">Category</th>
                    <th className="px-2 py-2 text-center text-[10px] font-semibold uppercase text-[#0f172a]">Qty</th>
                    <th className="px-2 py-2 text-right text-[10px] font-semibold uppercase text-[#0f172a]">Price</th>
                    <th className="px-2 py-2 text-right text-[10px] font-semibold uppercase text-[#0f172a]">Total Value</th>
                    <th className="px-2 py-2 text-center text-[10px] font-semibold uppercase text-[#0f172a]">Status</th>
                  </tr>
                </thead>
                <tbody>
                  {topAssets.map((item, i) => (
                    <tr key={i} className="border-b border-[#eef4fb]">
                      <td className="px-2 py-2 text-xs text-[#0f172a]">{item.name}</td>
                      <td className="px-2 py-2 font-mono text-xs text-[#475569]">{item.sku}</td>
                      <td className="px-2 py-2 text-xs text-[#334155]">{item.category}</td>
                      <td className="px-2 py-2 text-center text-xs text-[#0f172a]">{item.qty}</td>
                      <td className="px-2 py-2 text-right text-xs text-[#334155]">₱{item.price.toLocaleString()}</td>
                      <td className="px-2 py-2 text-right text-xs font-semibold text-[#0f172a]">₱{item.totalValue.toLocaleString()}</td>
                      <td className="py-2 px-2 text-center">
                        <span
                          className={`inline-block px-2 py-0.5 rounded text-[9px] font-semibold uppercase ${
                            item.stockStatus === "In Stock"
                              ? "bg-green-100 text-green-700"
                              : item.stockStatus === "Low Stock"
                              ? "bg-orange-100 text-orange-700"
                              : "bg-red-100 text-red-700"
                          }`}
                        >
                          {item.stockStatus}
                        </span>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>

            {/* Low Stock Alerts */}
            {lowStockAlerts.length > 0 && (
              <div className="mb-8">
                <h2 className="report-heading mb-4 flex items-center gap-2 border-b border-[#dbe4f0] pb-2 text-lg font-bold">
                  <AlertTriangle className="w-5 h-5 text-amber-500" />
                  Low Stock Alerts
                </h2>
                <div className="report-surface rounded-lg border border-[#dbe4f0] bg-[#fffaf0] p-4">
                  <table className="w-full">
                    <thead>
                      <tr className="border-b border-[#f6d6b8]">
                        <th className="py-2 text-left text-xs font-semibold text-[#92400e]">Asset</th>
                        <th className="py-2 text-left text-xs font-semibold text-[#92400e]">Category</th>
                        <th className="py-2 text-center text-xs font-semibold text-[#92400e]">Current</th>
                        <th className="py-2 text-center text-xs font-semibold text-[#92400e]">Minimum</th>
                        <th className="py-2 text-center text-xs font-semibold text-[#92400e]">Status</th>
                      </tr>
                    </thead>
                    <tbody>
                      {lowStockAlerts.map((item, i) => (
                        <tr key={i} className="border-b border-[#fce7d7] last:border-0">
                          <td className="py-2 text-xs text-[#0f172a]">
                            <div>{item.name}</div>
                            <div className="font-mono text-[10px] text-[#94a3b8]">{item.sku}</div>
                          </td>
                          <td className="py-2 text-xs text-[#334155]">{item.category}</td>
                          <td className="py-2 text-center text-xs font-semibold text-amber-700">{item.current}</td>
                          <td className="py-2 text-center text-xs text-[#334155]">{item.minimum}</td>
                          <td className="py-2 text-center">
                            <span className={`inline-block px-2 py-0.5 rounded text-[9px] font-semibold uppercase ${
                              item.current === 0 ? "bg-red-100 text-red-700" : "bg-orange-100 text-orange-700"
                            }`}>
                              {item.current === 0 ? "Out of Stock" : "Low Stock"}
                            </span>
                          </td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              </div>
            )}

            {/* Condition Summary */}
            <div className="mb-8">
              <h2 className="report-heading mb-4 border-b border-[#dbe4f0] pb-2 text-lg font-bold">
                Asset Condition Summary
              </h2>
              <div className="grid grid-cols-5 gap-3">
                {conditionData.map((item, i) => (
                  <div key={i} className="report-surface rounded-lg border border-[#dbe4f0] bg-[#f8fafc] p-3 text-center">
                    <div className="w-3 h-3 rounded-full mx-auto mb-2" style={{ backgroundColor: item.color }} />
                    <p className="text-xs font-medium text-[#334155]">{item.name}</p>
                    <p className="mt-1 text-xl font-bold text-[#0f172a]">{item.value}</p>
                    <p className="text-[10px] text-[#64748b]">{Math.round((item.value / conditionData.reduce((sum, d) => sum + d.value, 0)) * 100)}%</p>
                  </div>
                ))}
              </div>
            </div>

            {/* Footer */}
            <div className="mt-8 border-t-2 border-[#dbe4f0] pt-4">
              <div className="flex items-center justify-between text-xs text-[#64748b]">
                <p>Digital Minds BPO Services Inc.</p>
                <div className="flex items-center gap-4">
                  <p>Page 1</p>
                  <div className="w-6 h-6 bg-[#B0BF00] rounded" />
                </div>
              </div>
            </div>
          </div>
        </div>
      )}

      {/* Format Dialog */}
      <Dialog open={showFormatDialog} onOpenChange={setShowFormatDialog}>
        <DialogContent className="sm:max-w-md rounded-xl">
          <DialogHeader>
            <DialogTitle>Choose Report Format</DialogTitle>
            <DialogDescription>Select the format in which you want to generate the report.</DialogDescription>
          </DialogHeader>
          <div className="flex items-center justify-center gap-4 py-4">
            <button
              onClick={() => handleGenerateReport("pdf")}
              className="flex-1 flex flex-col items-center gap-2 px-6 py-4 bg-[#B0BF00] hover:bg-[#9aaa00] text-white rounded-lg font-medium transition-colors"
            >
              <FileText className="w-8 h-8" />
              <span className="text-sm">PDF Report</span>
              <span className="text-xs opacity-80">PDF format</span>
            </button>
            <button
              onClick={() => handleGenerateReport("csv")}
              className="flex-1 flex flex-col items-center gap-2 px-6 py-4 border-2 border-[#B0BF00] text-[#B0BF00] hover:bg-[#B0BF00]/5 rounded-lg font-medium transition-colors"
            >
              <File className="w-8 h-8" />
              <span className="text-sm">CSV Export</span>
              <span className="text-xs opacity-80">Spreadsheet format</span>
            </button>
          </div>
        </DialogContent>
      </Dialog>
    </>
  );
}
